name: yolox_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - cmake
  - cython
  - wheel
  - protobuf>=3.20.2
  - pip:
      - --extra-index-url https://download.pytorch.org/whl/cu118
      - torch==2.3.0+cu118
      - torchvision==0.18.0+cu118
      - torchaudio==2.3.0+cu118
      - onnxruntime==1.12.0
      - onnx==1.14.1
      - onnx-simplifier==0.3.5
      - onnxsim
      - scikit-image==0.25.2
      - opencv-python==4.10.0.84
      - thop==0.1.1-2209072238
      - loguru==0.7.3
      - ninja==1.13.0
      - pycocotools
      - numpy==1.26.4
      - tabulate==0.9.0
      - psutil
      - tensorboard==2.20.0
      - tqdm==4.67.1
      - matplotlib
      - Pillow==11.3.0
      - pycocotools==2.0.6
      - setuptools==58.0.4
      - scikit-learn

